# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: "3"

services:
  model-express-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - MODEL_EXPRESS_SERVER_PORT=8001
      - MODEL_EXPRESS_LOG_LEVEL=info
    restart: unless-stopped
