# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.persistence .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "modelexpress.fullname" . }}-pvc
  labels:
    {{- include "modelexpress.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ (.Values.persistence.accessMode | default "ReadWriteOnce") | quote }}
  {{- if and .Values.persistence .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "10Gi" }}
{{- end }}
